import Head from "next/head";
import Main from "../components/Main";
import "locomotive-scroll/dist/locomotive-scroll.css";
import { useEffect } from "react";
export default function Home() {
  useEffect(() => {
    import("locomotive-scroll").then((locomotiveModule) => {
      const ScrollEl = document.querySelector("#main-container");
      const scroll = new locomotiveModule.default({
        el: ScrollEl,
        smooth: true,
        multiplier: 1,
        class: "is-reveal",
      });
    });
  }, []);
  return (
    <>
      <Head>
        <title>NextJs + Gsap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="main-container">
        <Main />
      </div>
    </>
  );
}
